# Generated by Django 6.0.1 on 2026-01-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipboard',
            name='short_code',
        ),
    ]
