# Generated by Django 6.0.1 on 2026-01-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_clipboard_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='short_code',
            field=models.CharField(db_index=True, default=None, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
